CREATE TABLE CLIENTE (
    IDCLIENTE int  NOT NULL,
    NOME char(90)  NOT NULL,
    DATANASCIMENTO date  NOT NULL,
    CPF char(12)  NOT NULL,
    EMAIL char(50)  NOT NULL,
    TELEFONE char(12)  NULL,
    PRIMARY KEY (IDCLIENTE) );
CREATE TABLE CURSO (
    IDCURSO int  NOT NULL,
    NOME char(90)  NOT NULL,
    CARGAHORARIA int  NOT NULL,
    DESCRICAO char(120)  NOT NULL,
    PRIMARY KEY (IDCURSO) );
CREATE TABLE INSCRICAO (
    IDCLIENTE int  NOT NULL,
    IDCURSO int  NOT NULL,
    DATAINSCRICAO date  NOT NULL,
    DATACANCELAMENTO date  NULL,
    PRIMARY KEY (IDCLIENTE,IDCURSO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
    FOREIGN KEY (IDCURSO)   REFERENCES CURSO (IDCURSO) );
