-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-10-11 13:07:22.294

-- tables
-- Table: CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE int  NOT NULL,
    NOME char(90)  NOT NULL,
    DATANASCIMENTO date  NOT NULL,
    CPF char(12)  NOT NULL,
    EMAIL char(50)  NOT NULL,
    TELEFONE char(12)  NULL,
    CONSTRAINT IDCLIENTE PRIMARY KEY (IDCLIENTE)
);

-- Table: CURSO
CREATE TABLE CURSO (
    IDCURSO int  NOT NULL,
    NOME char(90)  NOT NULL,
    CARGAHORARIA int  NOT NULL,
    DESCRICAO char(120)  NOT NULL,
    CONSTRAINT CURSO_pk PRIMARY KEY (IDCURSO)
);

-- Table: INSCRICAO
CREATE TABLE INSCRICAO (
    IDCLIENTE int  NOT NULL,
    IDCURSO int  NOT NULL,
    DATAINSCRICAO date  NOT NULL,
    DATACANCELAMENTO date  NULL,
    CONSTRAINT IDCLIENTE PRIMARY KEY (IDCLIENTE,IDCURSO)
);

-- foreign keys
-- Reference: INSCRICAO_CLIENTE (table: INSCRICAO)
ALTER TABLE INSCRICAO ADD CONSTRAINT INSCRICAO_CLIENTE
    FOREIGN KEY (IDCLIENTE)
    REFERENCES CLIENTE (IDCLIENTE)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: INSCRICAO_CURSO (table: INSCRICAO)
ALTER TABLE INSCRICAO ADD CONSTRAINT INSCRICAO_CURSO
    FOREIGN KEY (IDCURSO)
    REFERENCES CURSO (IDCURSO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

